### ISSUE TITLE
Does not install with pip 18(?) and Python 2.7

### ISSUE THREAD

**Issue by gotomgo** [leovp/steamfiles#11]
Collecting steamfiles
  Using cached https://files.pythonhosted.org/packages/47/c0/fd94c8dacbe9f3762ddb21e6a52f5042def002f786b5cc5eb873412ad245/steamfiles-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2j/m1_mq4y539ncd1fzkkd6wj100000gn/T/pip-install-APIcdR/steamfiles/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
    

pip 18.0 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)

**Comment by leovp** [comment]
Python 2.7 is not supported, sorry. This particular issue can be fixed by installing from the latest master, but it still won't work on Python 2.7.
