### ISSUE TITLE
pip installation fails for pip version above 10

### ISSUE THREAD

**Issue by sakshatshinde** [leovp/steamfiles#14]
### **Steps to reproduce**
`pip install steamfiles`

###**Expected behavior**
Install !

### **Actual behavior**
ImportError: No module named 'pip.req'

### **System configuration**
Python version:
python 3.7
pip 10.0.1

I tried installing latest installation of pip tools, no luck

### **Hacky Solution**
Temporarily install pip version 9
`python -m pip install pip==9.0.3`
Install the package and then revert to the latest version

**Comment by sakshatshinde** [comment]
I couldn't find any other solution to this problem. Looks like downgrading is the only way to fix this.

**Comment by leovp** [comment]
Fixed in 0.1.4 (available on PyPI).
