### ISSUE TITLE
Please update steamfiles on PyPi

### ISSUE THREAD

**Issue by WinterPhoenix96** [leovp/steamfiles#15]
Several import changes have been made to steamfiles since it was last updated on PyPi.

8 commits, including support for [pip install-ing it on pip version 10 or above](https://github.com/leovp/steamfiles/commit/618dd0e5f7bd7aa880527a9b6ab7be53bfb2d552), support for VDF_VERSION 0x07564427 (Issue #5); both of which are issues I've encountered in the last 24 hours; and more have been added since July 2017.

Please and thanks for making such a useful library!

**Comment by leovp** [comment]
Done, the latest versions is 0.1.4 and it's available on PyPI.

**Comment by WinterPhoenix** [comment]
Thank you! ❤️
