### ISSUE TITLE
Pip install?

### ISSUE THREAD

**Issue by NullSoldier** [leovp/steamfiles#6]
Are you able to pip install steamfiles 0.1.2? I'm not sure the release is correct on pypi but I'm not sure if this is just an issue I am experiencing. Does the following work for you @leovp?

`pip install --no-cache-dir steamfiles==0.1.2`

**Comment by leovp** [comment]
Strangely it doesn't work for me too.
`pip -vv` tells me that it didn't even find `0.1.2`...
Take a look at https://pypi.python.org/simple/steamfiles/, there are only older versions.
I'll investigate.

**Comment by NullSoldier** [comment]
Boop. Any idea what's going on here? I think it may be uploaded but "unpublished" some how.

**Comment by leovp** [comment]
Reuploaded as `steamfiles 0.1.3` and it works. :\

**Comment by NullSoldier** [comment]
My man!
