### ISSUE TITLE
Does not install correctly with pip 9.0.3 on python 3.6

### ISSUE THREAD

**Issue by Destarianon** [leovp/steamfiles#8]
Repeatedly receiving an error installing it on python 3.6 with pip-tools 2.0.2 and pip 9.0.3.

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Destari\AppData\Local\Temp\pip-build-a5w5bws8\steamfiles\setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

**Comment by Destarianon** [comment]
Forgot to mention. I'm trying to install version 0.1.3

**Comment by leovp** [comment]
Thanks for reporting this. That API breakage wasn't nice.. 
Looks like someone fixed it in a PR, and it's now merged!

**Comment by boRk3D** [comment]
please release a new version on pypi
